# Generated by Django 3.1.3 on 2023-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweetphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comments_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tweetphoto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
